version: "2"
services:
  server:
    image: kaive/shadowsocks-libev
    ports:
      - 443:443
      - 443:443/udp
    volumes:
      - ./server.json:/server.json
    command: [ "ss-server", "-c","/server.json","-u"]
    build: .
    restart: always
    container_name: ss-server

  local:
    image: kaive/shadowsocks-libev
    ports:
      - 1080:1080
      - 1080:1080/udp
    volumes:
      - ./client.json:/client.json
    command: [ "ss-local", "-c","/client.json","-u"]
    build: .
    container_name: ss-local

  redir:
    image: kaive/shadowsocks-libev
    ports:
      - 1081:1080
      - 1081:1080/udp
    volumes:
      - ./client.json:/client.json
    command: [ "ss-redir", "-c","/client.json"]
    build: .
    container_name: ss-redir

  tunnel:
    image: kaive/shadowsocks-libev
    ports:
      - 5300:1080
      - 5300:1080/udp
    volumes:
      - ./client.json:/client.json
    command: [ "ss-tunnel", "-c","/client.json","-L","8.8.8.8:53","-u"]
    build: .
    container_name: ss-tunnel